In [1]:
!pip install numpy

In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[1,2,3,4],[7,8,9,10]])
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
b.shape

(2, 4)

In [7]:
a.shape

(4,)

In [8]:
b.dtype

dtype('int32')

In [9]:
c=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [10]:
c=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c[1,1]

2